"""
Copyright (c) 2023 Omer Duskin.

This file is part of Opensubtitles API wrapper.

Opensubtitles API is free software: you can redistribute it and/or modify
it under the terms of the MIT License as published by the Massachusetts
Institute of Technology.

For full details, please see the LICENSE file located in the root
directory of this project.
"""

language_codes = {
    "af": "Afrikaans",
    "sq": "Albanian",
    "ar": "Arabic",
    "an": "Aragonese",
    "hy": "Armenian",
    "at": "Asturian",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bs": "Bosnian",
    "br": "Breton",
    "bg": "Bulgarian",
    "my": "Burmese",
    "ca": "Catalan",
    "zh-cn": "Chinese (simplified)",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "ka": "Georgian",
    "de": "German",
    "gl": "Galician",
    "el": "Greek",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "it": "Italian",
    "ja": "Japanese",
    "kk": "Kazakh",
    "km": "Khmer",
    "ko": "Korean",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "lb": "Luxembourgish",
    "mk": "Macedonian",
    "ml": "Malayalam",
    "ms": "Malay",
    "ma": "Manipuri",
    "mn": "Mongolian",
    "no": "Norwegian",
    "oc": "Occitan",
    "fa": "Persian",
    "pl": "Polish",
    "pt-pt": "Portuguese",
    "ru": "Russian",
    "sr": "Serbian",
    "si": "Sinhalese",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "sw": "Swahili",
    "sv": "Swedish",
    "sy": "Syriac",
    "ta": "Tamil",
    "te": "Telugu",
    "tl": "Tagalog",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "uz": "Uzbek",
    "vi": "Vietnamese",
    "ro": "Romanian",
    "pt-br": "Portuguese (Brazilian)",
    "me": "Montenegrin",
    "zh-tw": "Chinese (traditional)",
    "ze": "Chinese bilingual",
    "nb": "Norwegian Bokmal",
    "se": "Northern Sami",
}
